/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as splatRouteImport } from './routes/$'
import { Route as SectionRssDotxmlRouteImport } from './routes/$section.rss[.]xml'
import { Route as IndexRouteImport } from './../.livemark/routes/index'

const splatRoute = splatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRssDotxmlRoute = SectionRssDotxmlRouteImport.update({
  id: '/$section/rss.xml',
  path: '/$section/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof splatRoute
  '/$section/rss.xml': typeof SectionRssDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof splatRoute
  '/$section/rss.xml': typeof SectionRssDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof splatRoute
  '/$section/rss.xml': typeof SectionRssDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/$section/rss.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/$section/rss.xml'
  id: '__root__' | '/' | '/$' | '/$section/rss.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  splatRoute: typeof splatRoute
  SectionRssDotxmlRoute: typeof SectionRssDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof splatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/rss.xml': {
      id: '/$section/rss.xml'
      path: '/$section/rss.xml'
      fullPath: '/$section/rss.xml'
      preLoaderRoute: typeof SectionRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  splatRoute: splatRoute,
  SectionRssDotxmlRoute: SectionRssDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
